name: Build and push to gh-pages
on:
  push:
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: totaldebug/sphinx-publish-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sphinx_src: 'source'
          target_branch: 'gh-pages'
